### PR TITLE
fix(clock): Call performance.now as a method. Add new RelativeClock

### LINKED ISSUE #69: TypeError calling performance.now
I mentioned it in [a comment](https://github.com/mostjs/core/pull/63/files#r120018903) in a closed PR so I'm opening an issue here.

The `performance.now` method is being called as a function without binding `this` to `performance` and it's causing an error. I guess this wasn't detected in testing because the tests run in a node.js environment?

### PR DESCRIPTION
**Pull request by briancavalier**
Fix #69 
Close #71 

Consider `Date` and `performance` to be acceptable `Clock` types.   Add new RelativeClock that accepts any `Clock` and creates a new `Clock` relative to its current time.

### CODE REVIEW

File: packages/scheduler/src/clock.js [hunk 1]
```diff
@@ -2,37 +2,37 @@
...
   now () {
-    const hrt = this._hrtime(this.origin)
+    const hrt = this.hrtime(this.origin)
     return (hrt[0] * 1e9 + hrt[1]) / 1e6
   }
 }
 
-export const millisecondClockFromNow = now =>
-  new MillisecondClock(now, now())
+export const relativeClock = clock =>
```
Comment (frangio) [inline packages/scheduler/src/clock.js]: Should this be called `newRelativeClock` for consistency with the other exported functions?

File: packages/scheduler/src/clock.js [hunk 2]
```diff
@@ -2,37 +2,37 @@
...
+  new RelativeClock(clock, clock.now())
 
 export const newPerformanceNowClock = () =>
```
Comment (frangio) [inline packages/scheduler/src/clock.js]: How about `newPerformanceClock`?

File: packages/scheduler/src/clock.js [hunk 3]
```diff
@@ -2,37 +2,37 @@
...
-  millisecondClockFromNow(performance.now)
+  relativeClock(performance)
 
 export const newDateNowClock = () =>
```
Comment (frangio) [inline packages/scheduler/src/clock.js]: ... and `newDateClock`?

File: packages/scheduler/src/clock.js (hunk 1 above)
Comment (briancavalier) [inline packages/scheduler/src/clock.js]: We've been using `new*` for creating a new thing from nothing, or from its component pieces.  This case is kind of interesting because we're transforming a clock.  It's more like `Array#map` than `new Array`.  Any suggestions on a name that means "transform a clock"?

Ideas: `relativeTo`, `withOrigin`

File: packages/scheduler/src/clock.js (hunk 2 above)
Comment (briancavalier) [inline packages/scheduler/src/clock.js]: Good call :+1:

File: packages/scheduler/src/clock.js (hunk 1 above)
Comment (frangio) [inline packages/scheduler/src/clock.js]: Oh, I see. It's actually more like `Array#from` IMO. So with that as an idea, how about `relativeClockFrom`? I'm not sure that it fits with most's naming conventoins, or that it's better than just `relativeClock`.

Comment (briancavalier) [inline packages/scheduler/src/clock.js]: Good suggestion, thanks.  It spawned quite a bit of discussion among the core team!  We finally decided on `clockRelativeTo`.  I think we'll probably add a similar `schedulerRelativeTo` in #67.

**Comment by briancavalier** [comment]
@frangio We just published `@most/scheduler` and `@most/core` 0.7.1 with this fix.  When you have a chance, please let us know if it's working for you.
